/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const UnlockedAchievement = IDL.Record({
  'achievementId' : IDL.Text,
  'unlockTime' : Time,
});
export const UserProfile = IDL.Record({
  'username' : IDL.Text,
  'avatar' : IDL.Nat,
});
export const Difficulty = IDL.Variant({
  'easy' : IDL.Null,
  'hard' : IDL.Null,
  'medium' : IDL.Null,
});
export const ScoreEntry = IDL.Record({
  'player' : IDL.Principal,
  'game' : IDL.Text,
  'difficulty' : Difficulty,
  'score' : IDL.Nat,
  'timestamp' : Time,
});
export const PlayerSummary = IDL.Record({
  'username' : IDL.Text,
  'gamesPlayed' : IDL.Nat,
  'achievementCount' : IDL.Nat,
  'totalPoints' : IDL.Nat,
  'avatar' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createOrUpdateProfile' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'getAchievements' : IDL.Func([], [IDL.Vec(UnlockedAchievement)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getLeaderboard' : IDL.Func([IDL.Text], [IDL.Vec(ScoreEntry)], ['query']),
  'getPersonalStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'scores' : IDL.Vec(ScoreEntry),
          'bestScores' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
        }),
      ],
      ['query'],
    ),
  'getPlayerSummary' : IDL.Func([], [PlayerSummary], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitScore' : IDL.Func([IDL.Text, IDL.Nat, Difficulty], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const UnlockedAchievement = IDL.Record({
    'achievementId' : IDL.Text,
    'unlockTime' : Time,
  });
  const UserProfile = IDL.Record({ 'username' : IDL.Text, 'avatar' : IDL.Nat });
  const Difficulty = IDL.Variant({
    'easy' : IDL.Null,
    'hard' : IDL.Null,
    'medium' : IDL.Null,
  });
  const ScoreEntry = IDL.Record({
    'player' : IDL.Principal,
    'game' : IDL.Text,
    'difficulty' : Difficulty,
    'score' : IDL.Nat,
    'timestamp' : Time,
  });
  const PlayerSummary = IDL.Record({
    'username' : IDL.Text,
    'gamesPlayed' : IDL.Nat,
    'achievementCount' : IDL.Nat,
    'totalPoints' : IDL.Nat,
    'avatar' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createOrUpdateProfile' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'getAchievements' : IDL.Func([], [IDL.Vec(UnlockedAchievement)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getLeaderboard' : IDL.Func([IDL.Text], [IDL.Vec(ScoreEntry)], ['query']),
    'getPersonalStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'scores' : IDL.Vec(ScoreEntry),
            'bestScores' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
          }),
        ],
        ['query'],
      ),
    'getPlayerSummary' : IDL.Func([], [PlayerSummary], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitScore' : IDL.Func([IDL.Text, IDL.Nat, Difficulty], [], []),
  });
};

export const init = ({ IDL }) => { return []; };