/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Difficulty = { 'easy' : null } |
  { 'hard' : null } |
  { 'medium' : null };
export interface PlayerSummary {
  'username' : string,
  'gamesPlayed' : bigint,
  'achievementCount' : bigint,
  'totalPoints' : bigint,
  'avatar' : bigint,
}
export interface ScoreEntry {
  'player' : Principal,
  'game' : string,
  'difficulty' : Difficulty,
  'score' : bigint,
  'timestamp' : Time,
}
export type Time = bigint;
export interface UnlockedAchievement {
  'achievementId' : string,
  'unlockTime' : Time,
}
export interface UserProfile { 'username' : string, 'avatar' : bigint }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createOrUpdateProfile' : ActorMethod<[string, bigint], undefined>,
  'getAchievements' : ActorMethod<[], Array<UnlockedAchievement>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getLeaderboard' : ActorMethod<[string], Array<ScoreEntry>>,
  'getPersonalStats' : ActorMethod<
    [],
    { 'scores' : Array<ScoreEntry>, 'bestScores' : Array<[string, bigint]> }
  >,
  'getPlayerSummary' : ActorMethod<[], PlayerSummary>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitScore' : ActorMethod<[string, bigint, Difficulty], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];